### ISSUE TITLE
Find real-world data

### ISSUE THREAD

**Issue by zegkljan** [s3-food-justice/food-justice#5]
Find some data related to food (or other resource) waste/production/distribution.

**Comment by VicientReno** [comment]
[https://datacatalog.worldbank.org/dataset/what-waste-global-database]
The link of real-world data.

**Comment by VicientReno** [comment]
https://www.ers.usda.gov/topics/food-nutrition-assistance/food-security-in-the-us/key-statistics-graphics.aspx

The Data of Level Prevalence of Food Insecurity in United State.
